triggers:
  flow-listener-1:
    name: Flow Listener
    parameters:
      id: prepareJiraHeaders
    enabled: true
    invoke:
      flow: prepareJiraHeaders
      parameters:
        request: $.request
        config: $.config
        env: $.env
  flow-listener-2:
    name: getAmplifyAPIHeaders
    parameters:
      id: getAmplifyAPIHeaders
    enabled: true
    invoke:
      flow: getAmplifyAPIHeaders
      parameters:
        request: $.request
        config: $.config
        env: $.env
